[package]
name = "rustapple"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
ffmpeg-next = "7.0.0"
image = "0.25.1"
log = "0.4.21"
rodio = "0.18.0"
simple_logger = "5.0.0"
video-rs = "0.7.4"
